### ISSUE TITLE
why image_lab is  <class 'NoneType'> ? 

### ISSUE THREAD

**Issue by AMEERAZAM08** [bcmi/DucoNet-Image-Harmonization#1]
def predict(self, image, mask, image_lab = None,return_numpy=True):
        with torch.no_grad():
            for transform in self.transforms:
                image, mask = transform.transform(image, mask)

            transform = transforms.Compose([
                transforms.ToTensor(),
             ])
            print(type(image_lab))
            comp_image_lab = transform(image_lab).unsqueeze(0).to(self.device)
            predicted_output = self.net(image, mask,image_lab = comp_image_lab)
            predicted_image = predicted_output['images']

            for transform in reversed(self.transforms):
                predicted_image = transform.inv_transform(predicted_image)

            predicted_image = torch.clamp(predicted_image, 0, 255)

        if return_numpy:
            return predicted_image.cpu().numpy()
        else:
            return predicted_image
why image_lab is  <class 'NoneType'> ? 
getting error: 

  File "/home/rnd/miniconda3/envs/e4s/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 138, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'NoneType'>

**Comment by AMEERAZAM08** [comment]
@ustcnewly @ZeroFlt  Please help me out asap

**Comment by ZeroFlt** [comment]
Are you doing the evaluation on test dataset? Is the path to the error reported in the file iharm/inference/predictor.py ,line 38?

**Comment by AMEERAZAM08** [comment]
yes but while inference image_lab sending as None in net. 
python  test.py  DucoNet ./checkpoints/last_model/DucoNet1024.pth  --images ./image  --masks \
             ./mask --config-path  ./config.yml --gpu 0 --resize 1024
i did minor change for inference

**Comment by ZeroFlt** [comment]
In our code, image_lab will be obtained in the dataloader (iharm/data/hdataset.py line40) after a colour space transformation of cv2.COLOR_RGB2Lab. Then it is taken out in iharm/inference/evaluation.py (Line 18) and passed to predictor.predict function (Line 22). If you change the code or rewrite the dataloader, you may need to do RGB to Lab color space transformation to get the corresponding Lab color space image.

**Comment by AMEERAZAM08** [comment]
thanks
