### ISSUE TITLE
predict_for_dir.py

### ISSUE THREAD

**Issue by SmallXieGithub** [bcmi/DucoNet-Image-Harmonization#3]
你好，我在运行predict_for_dir.py的时候
https://github.com/bcmi/DucoNet-Image-Harmonization/blob/6ddfad6a12aff2814eab539672fecaf07fc1a58f/iharm/inference/predictor.py#L38C40-L38C49 报错image_lab None

**Comment by ZeroFlt** [comment]
你可以参考一下这里的解决方式#1
